# Generated by Django 4.1 on 2022-09-13 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_section_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replie',
            name='post',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('replies', models.ManyToManyField(blank=True, to='forum.replie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.profile')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='forum.comment'),
        ),
    ]
