# Generated by Django 4.1 on 2022-09-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_replie_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
