# Generated by Django 4.1 on 2022-09-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replie',
            name='is_solution',
            field=models.BooleanField(default=False),
        ),
    ]
